"""simavr board harness: generates, compiles and describes it.

simavr's core emulates the MCU. Peripherals (LEDs, buttons, displays, serial
sinks) live in libsimavrparts and must be wired to the core's IRQs by a small
host program. That program is generated here from CLI flags, so users never
write it by hand.

Recipes encoded below (each one documented in docs/simulator.md):

* output pin / LED  — a PORT write raises IOPORT_IRQ_PIN_ALL carrying the whole
  8-bit pin state; indices 0..7 are the INPUT side and never fire for a driven
  pin, which is the classic simavr trap.
* input pin / button — the `button` part drives the pin low, auto-releases, and
  is connected to that pin's input IRQ.
* serial — UART_IRQ_OUTPUT for bytes the MCU sends, UART_IRQ_INPUT to feed it.
"""

from __future__ import annotations

import os

from .util import C_DIM, c_string, require, run, step, warn

HARNESS_TEMPLATE = r"""/*
 * GENERATED by `mcu board` — simavr board harness for {name}.
 *
 * LEDs and buttons are not part of simavr: they are parts from libsimavrparts
 * wired to the AVR's IRQs here, which is the headless equivalent of dropping an
 * LED on a pin and clicking a button in a vendor IDE simulator.
 *
 * Do not edit — rerun `mcu board` with different flags instead.
 */
#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#if !defined(_WIN32)
#include <sys/select.h>
#endif

#include "sim_avr.h"
#include "sim_elf.h"
#include "sim_irq.h"
#include "sim_cycle_timers.h"
#include "avr_ioport.h"
#include "avr_uart.h"
#include "button.h"

#define N_LEDS    {nleds}
#define N_BUTTONS {nbuttons}
#define N_PRESSES {npresses}
#define N_RX      {nrx}

typedef struct {{ char port; int bit; const char *name; }} led_cfg_t;
typedef struct {{ char port; int bit; }} button_cfg_t;
typedef struct {{ int btn; unsigned at_ms; unsigned hold_ms; }} press_cfg_t;
typedef struct {{ unsigned at_ms; char text[64]; }} rx_cfg_t;

static const led_cfg_t    leds[]    = {{ {leds}
}};
static const button_cfg_t buttons[] = {{ {buttons}
}};
static const press_cfg_t  presses[] = {{ {presses}
}};
static const rx_cfg_t     rxs[]     = {{ {rx}
}};

static avr_t    *avr;
static button_t  btn[N_BUTTONS ? N_BUTTONS : 1];
static avr_irq_t *uart_rx_irq;
static int       led_state[N_LEDS ? N_LEDS : 1];
static unsigned  led_edges, presses_done;
static int       use_uart = {uart}, use_keys = {keys};

static double sim_ms(void)
{{
    return avr->cycle / (double)(avr->frequency / 1000UL);
}}

static void led_hook(struct avr_irq_t *irq, uint32_t value, void *param)
{{
    (void)irq;
    char port = (char)(uintptr_t)param;
    for (int i = 0; i < N_LEDS; i++) {{
        if (leds[i].port != port) continue;
        int b = (value >> leds[i].bit) & 1;
        if (b == led_state[i]) continue;
        led_state[i] = b;
        led_edges++;
        printf("[led    %9.2f ms] %-5s -> %s  (PORT%c=0x%02x)\n",
               sim_ms(), leds[i].name, b ? "ON " : "off", port, value);
    }}
}}

static void uart_hook(struct avr_irq_t *irq, uint32_t value, void *param)
{{
    (void)irq; (void)param;
    char c = (char)value;
    if (c != '\r') {{ fputc(c, stdout); fflush(stdout); }}   /* firmware sends CRLF */
}}

static void press_button(int idx, unsigned hold_ms)
{{
    if (idx < 0 || idx >= N_BUTTONS) return;
    presses_done++;
    printf("[button %9.2f ms] press P%c%d (hold %u ms)\n",
           sim_ms(), buttons[idx].port, buttons[idx].bit, hold_ms);
    button_press(&btn[idx], hold_ms * 1000);
}}

/* avr_cycle_timer_register_usec() is relative to now, and re-registering the
 * same (callback, param) pair cancels the earlier timer — so every scheduled
 * event carries its own param. */
static avr_cycle_count_t press_cb(avr_t *a, avr_cycle_count_t when, void *param)
{{
    (void)a; (void)when;
    press_cfg_t *p = param;
    press_button(p->btn, p->hold_ms);
    return 0;
}}

static avr_cycle_count_t rx_cb(avr_t *a, avr_cycle_count_t when, void *param)
{{
    (void)a; (void)when;
    rx_cfg_t *r = param;
    printf("[uart_rx%9.2f ms] inject \"%s\"\n", sim_ms(), r->text);
    for (const char *p = r->text; *p; p++)
        avr_raise_irq(uart_rx_irq, (uint8_t)*p);
    return 0;
}}

static void check_keys(void)
{{
#if !defined(_WIN32)
    if (!use_keys) return;
    static unsigned n;
    if ((++n & 0x1f) != 0) return;
    fd_set fds; struct timeval zero = {{ 0, 0 }};
    FD_ZERO(&fds); FD_SET(STDIN_FILENO, &fds);
    if (select(STDIN_FILENO + 1, &fds, NULL, NULL, &zero) <= 0) return;
    char c;
    if (read(STDIN_FILENO, &c, 1) != 1) return;
    if (c == 'q') exit(0);
    if (c == 'b') {{ press_button(0, 200); return; }}
    if (uart_rx_irq) {{
        printf("[uart_rx%9.2f ms] inject '%c'\n", sim_ms(), c);
        avr_raise_irq(uart_rx_irq, (uint8_t)c);
    }}
#endif
}}

int main(int argc, char **argv)
{{
    const char *fw = "{source}";
    double max_ms = 0;
    for (int i = 1; i < argc; i++) {{
        if (!strcmp(argv[i], "--seconds") && i + 1 < argc)
            max_ms = atof(argv[++i]) * 1000.0;
        else if (argv[i][0] != '-')
            fw = argv[i];
    }}

    elf_firmware_t f;
    memset(&f, 0, sizeof(f));
    if (elf_read_firmware(fw, &f) != 0) {{
        fprintf(stderr, "board: cannot read firmware '%s'\n", fw);
        return 1;
    }}
    strcpy(f.mmcu, "{mcu}");
    f.frequency = {freq};

    avr = avr_make_mcu_by_name(f.mmcu);
    if (!avr) {{ fprintf(stderr, "board: unknown mcu '%s'\n", f.mmcu); return 1; }}
    avr_init(avr);
    avr_load_firmware(avr, &f);

    /* libsimavr prints UART TX itself at log >= LOG_OUTPUT (colourised, CR shown
     * as '.'): silence it so our hook is the only writer. */
    avr->log = 0;

    for (int i = 0; i < N_LEDS; i++) {{
        char seen = 0;
        for (int j = 0; j < i; j++)
            if (leds[j].port == leds[i].port) seen = 1;
        if (seen) continue;                 /* one notify per port is enough */
        avr_irq_register_notify(
            avr_io_getirq(avr, AVR_IOCTL_IOPORT_GETIRQ(leds[i].port),
                          IOPORT_IRQ_PIN_ALL),
            led_hook, (void *)(uintptr_t)leds[i].port);
    }}

    uart_rx_irq = avr_io_getirq(avr, AVR_IOCTL_UART_GETIRQ('0'), UART_IRQ_INPUT);
    if (use_uart)
        avr_irq_register_notify(
            avr_io_getirq(avr, AVR_IOCTL_UART_GETIRQ('0'), UART_IRQ_OUTPUT),
            uart_hook, NULL);

    for (int i = 0; i < N_BUTTONS; i++) {{
        char nm[8];
        snprintf(nm, sizeof(nm), "P%c%d", buttons[i].port, buttons[i].bit);
        button_init(avr, &btn[i], nm);
        avr_connect_irq(btn[i].irq + IRQ_BUTTON_OUT,
                        avr_io_getirq(avr, AVR_IOCTL_IOPORT_GETIRQ(buttons[i].port),
                                      buttons[i].bit));
    }}
    for (int i = 0; i < N_PRESSES; i++)
        avr_cycle_timer_register_usec(avr, presses[i].at_ms * 1000, press_cb,
                                      (void *)&presses[i]);
    for (int i = 0; i < N_RX; i++)
        avr_cycle_timer_register_usec(avr, rxs[i].at_ms * 1000, rx_cb,
                                      (void *)&rxs[i]);

    printf("board: %s (%s @ %u Hz)\n", fw, f.mmcu, f.frequency);
    printf("  leds:%d  buttons:%d  uart:%s%s\n", N_LEDS, N_BUTTONS,
           use_uart ? "on" : "off",
           use_keys ? "   keys: 'b' press, 'q' quit, other = serial RX" : "");
    printf("  --------------------------------------------------------------\n");

    for (;;) {{
        int st = avr_run(avr);
        if (st == cpu_Done || st == cpu_Crashed) {{
            printf("\nboard: CPU stopped (state %d) at %.2f ms\n", st, sim_ms());
            break;
        }}
        if (max_ms > 0 && sim_ms() >= max_ms) break;
        check_keys();
    }}
    printf("board: %u led edge(s), %u press(es), %.2f ms simulated\n",
           led_edges, presses_done, sim_ms());
    return 0;
}}
"""


class Peripherals:
    """Parsed --led/--button/--press/--rx flags."""

    def __init__(self, leds=(), buttons=(), presses=(), rx=()):
        self.leds = list(leds)          # (port, bit, label)
        self.buttons = list(buttons)    # (port, bit)
        self.presses = list(presses)    # (button index, at_ms, hold_ms)
        self.rx = list(rx)              # (at_ms, text)


def render(proj, periph: Peripherals, uart=True, keys=False, source=None) -> str:
    led_entries = "\n".join(
        f'  {{ \'{p}\', {b}, "{name}" }},' for p, b, name in periph.leds) or "  { 0, 0, 0 },"
    btn_entries = "\n".join(
        f'  {{ \'{p}\', {b} }},' for p, b in periph.buttons) or "  { 0, 0 },"
    press_entries = "\n".join(
        f"  {{ {i}, {at:.0f}, {hold:.0f} }}," for i, at, hold in periph.presses) \
        or "  { 0, 0, 0 },"
    rx_entries = "\n".join(
        "  { %d, %s }," % (at, c_string(t)) for at, t in periph.rx) or '  { 0, "" },'

    return HARNESS_TEMPLATE.format(
        name=proj.name, mcu=proj.mcu, freq=proj.freq,
        source=source or proj.elf,
        nleds=len(periph.leds), nbuttons=len(periph.buttons),
        npresses=len(periph.presses), nrx=len(periph.rx),
        leds=led_entries, buttons=btn_entries,
        presses=press_entries, rx=rx_entries,
        uart=1 if uart else 0, keys=1 if keys else 0,
    )


def generated_dir(proj) -> str:
    return os.path.join(proj.dir, "sim", "generated")


def build(proj, periph: Peripherals, *, prefix="/usr/local", cc="cc",
          uart=True, keys=False, dry=False, force=False) -> str:
    """Write + compile the harness; returns the binary path."""
    require("simavr", dry, why="the harness links against libsimavrparts")
    gen = generated_dir(proj)
    src = os.path.join(gen, "board.c")
    binary = os.path.join(gen, "board")
    os.makedirs(gen, exist_ok=True)

    text = render(proj, periph, uart=uart, keys=keys)
    old = None
    if os.path.isfile(src):
        with open(src) as fh:
            old = fh.read()
    if old != text or force or not os.path.isfile(binary):
        with open(src, "w") as fh:
            fh.write(text)

    inc = os.path.join(prefix, "include", "simavr")
    if not os.path.isdir(inc) and not dry:
        warn(f"simavr headers not found in {inc} — set SIMAVR_PREFIX")

    cmd = [cc, "-O2", "-g", "-Wall",
           f"-I{inc}", f"-I{os.path.join(inc, 'parts')}",
           "-o", binary, src,
           f"-L{os.path.join(prefix, 'lib')}",
           "-lsimavrparts", "-lsimavr", "-lelf", "-lm"]
    step(f"harness: {len(periph.leds)} led(s), {len(periph.buttons)} button(s)"
         + (", uart" if uart else ""))
    rc, out = run(cmd, dry=dry, capture=True, check=False)
    if rc != 0:
        print(out)
        print(f"{C_DIM}     hint: point SIMAVR_PREFIX at the simavr install "
              f"prefix (currently {prefix}){C_DIM}{'':0s}")
        from .util import die as _die
        _die("harness build failed")
    return binary
